### ISSUE TITLE
Oblique warning about CommonJS at build time.

### ISSUE THREAD

**Issue by ice-blaze** [oblique-bit/oblique#31]
Hello, 

When I'm building my project I have this kind of warning: 
```
src/app/app.module.ts depends on '@oblique/oblique'. CommonJS or AMD dependencies can cause optimisation bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies`
```
 Is it normal? Is there a way to avoid it?
 
 My current version of oblique is 6.1.5 and using Angular 12 (I know it's not tested yet but if other have similar issues I was curious about) 
 
The import look like this 
```
import {
  ObDocumentMetaService,
  ObMasterLayoutConfig,
  multiTranslateLoader,
  TRANSLATION_FILES,
  ObliqueModule,
} from '@oblique/oblique';
```

**Comment by gillerr** [comment]
Hi

This warning is caused by AJV, a dependency of Oblique. This is solved with Oblique 7.

If you want to get rid of it, you can just deactivate it; https://angular.io/guide/build#configuring-commonjs-dependencies

**Comment by ice-blaze** [comment]
Oh OK, then I'll close the issue and wait for Oblique 7. Thank you for your help.

**Comment by fischermatte** [comment]
fyi: warning is still present in v7.

**Comment by gillerr** [comment]
This is related to how AJV is packaged, meaning there are not lots of solutions.
1. We could replace AJV
2. We could wait for an update to AJV that solves the problem
3. We could configure Oblique to use secondary entry points to mitigate the problem

The first solution will be costly and is a breaking change in any case. I'm not sure at all that other libraries won't have the same problem. This mean this is not an option, at least on the short term

The second solution provides absolutely no guarantees.  Even worse, AJV have already been adapted as ESM instead of CommonJS, meaning this should already be fixed. Anyway, we'll keep up to date with the new versions.

The third solution is only a partial one. The warning would still be there but only when the `ObValidationModule` is actually imported. This solution is already on our Radar to solve some performance problems so we'll definitely have a look at it.

**Comment by fischermatte** [comment]
@gillerr was there some progress with Oblique 9 on this? I still see this warning.

**Comment by nina-egger** [comment]
No solution has been found yet. We are looking to find a solution but it will not be fixed/solved soon.

This issue will stay open until then.

**Comment by nina-egger** [comment]
The warnings can be disabled by adding the following in the angular.json:
` 
...
"build": {
          ...
          "options": {
            "allowedCommonJsDependencies": ["ajv", "ajv-formats"],
`
So that is a possible workaround. 

@gillerr we've got schemaitcs that add this I think. Do we keep this issue here?
